### ISSUE TITLE
Add user records and create Role model

### ISSUE THREAD

**Issue by BenMukebo** [BenMukebo/health-care-online-system#11]
- [ ] Create Role model.
- [ ] Add  profile, address and the matricule_number  record to the User model

> Hey @BenMukebo and @vic778 
> I'm not sure I got your reason for not using the role model; I mean want to be able to query different users based on their roles.
> You can have a look at this article to learn more.
> 
> https://culttt.com/2016/01/20/implementing-roles-and-permissions-in-ruby-on-rails
> 
> _Originally posted by @Tresor11 in https://github.com/BenMukebo/health-care-online-system/issues/3#issuecomment-1504913299_
>

**Comment by BenMukebo** [comment]
Hello @Tresor11, Do you think it's necessary to create an `Assignment` model that will associate a Role to a User at this stage?

**Comment by Tresor11** [comment]
I don't think we ned that Assignment model considering that we already have a Role model
